[DNM] ci: clang: use ubuntu-latest

diff --git a/.github/workflows/clang.yaml b/.github/workflows/clang.yaml
--- a/.github/workflows/clang.yaml
+++ b/.github/workflows/clang.yaml
@@ -11,7 +11,7 @@ jobs:
         with:
           access_token: ${{ github.token }}
   clang-build:
-    runs-on: zephyr_runner
+    runs-on: ubuntu-latest
     needs: clang-build-prep
     container:
       image: zephyrprojectrtos/ci:v0.21.0
@@ -40,11 +40,11 @@ jobs:
         run: |
           pip3 install GitPython
           echo "$HOME/.local/bin" >> $GITHUB_PATH
-          git config --global user.email "bot@zephyrproject.org"
-          git config --global user.name "Zephyr Bot"
+          # git config --global user.email "bot@zephyrproject.org"
+          # git config --global user.name "Zephyr Bot"
           rm -fr ".git/rebase-apply"
-          git rebase origin/${BASE_REF}
-          git log  --pretty=oneline | head -n 10
+          # git rebase origin/${BASE_REF}
+          # git log  --pretty=oneline | head -n 10
           west init -l . || true
           west config --global update.narrow true
           # In some cases modules are left in a state where they can't be
@@ -52,7 +52,7 @@ jobs:
           # So first retry to update, if that does not work, remove all modules
           # and start over. (Workaround until we implement more robust module
           # west caching).
-          west update --path-cache /github/cache/zephyrproject 2>&1 1> west.log || west update --path-cache /github/cache/zephyrproject 2>&1 1> west2.log || ( rm -rf ../modules ../bootloader ../tools && west update --path-cache /github/cache/zephyrproject)
+          # west update --path-cache /github/cache/zephyrproject 2>&1 1> west.log || west update --path-cache /github/cache/zephyrproject 2>&1 1> west2.log || ( rm -rf ../modules ../bootloader ../tools && west update --path-cache /github/cache/zephyrproject)
 
       - name: Check Environment
         run: |
@@ -68,13 +68,16 @@ jobs:
           export ZEPHYR_TOOLCHAIN_VARIANT=llvm
 
           # check if we need to run a full twister or not based on files changed
-          python3 ./scripts/ci/test_plan.py --platform ${{ matrix.platform }} -c origin/${BASE_REF}..
+          # python3 ./scripts/ci/test_plan.py --platform ${{ matrix.platform }} -c origin/${BASE_REF}..
 
           # We can limit scope to just what has changed
           if [ -s testplan.csv ]; then
             # Full twister but with options based on changes
-            ./scripts/twister --inline-logs -M -N -v --load-tests testplan.csv --retry-failed 2
+            # ./scripts/twister --inline-logs -M -N -v --load-tests testplan.csv --retry-failed 2
           fi
+
+          mkdir twister-out
+          cp twister.xml twister-out/
 
       - name: Upload Unit Test Results
         if: always()
